# DigitalOcean Agent Development Kit (ADK) Service for NEXUS
# Manages AI agent creation, testing, and deployment

import os
import subprocess
import json
import asyncio
from pathlib import Path
from typing import Dict, List, Optional, Any
from datetime import datetime
import shutil

class DigitalOceanADKService:
    """Service for managing DigitalOcean AI agents using the Agent Development Kit"""
    
    def __init__(self):
        self.workspace_root = Path("/app/backend/agent_workspace")
        self.workspace_root.mkdir(exist_ok=True)
        
        # Get API keys from environment
        self.gradient_model_key = os.getenv("GRADIENT_MODEL_ACCESS_KEY")
        self.do_api_token = os.getenv("DIGITALOCEAN_API_TOKEN")
        
        # ADK configuration
        self.adk_available = self._check_adk_availability()
        
    def _check_adk_availability(self) -> bool:
        """Check if ADK is available"""
        try:
            result = subprocess.run(
                ["gradient", "--version"],
                capture_output=True,
                text=True,
                timeout=5
            )
            return result.returncode == 0
        except Exception:
            return False
    
    async def create_agent(
        self,
        agent_name: str,
        deployment_name: str = "development",
        description: str = "",
        model: str = "openai-gpt-oss-120b"
    ) -> Dict[str, Any]:
        """
        Create a new AI agent using ADK
        
        Args:
            agent_name: Name of the agent workspace
            deployment_name: Deployment environment name
            description: Agent description
            model: Model to use for the agent
            
        Returns:
            Dict with agent creation status and details
        """
        try:
            agent_path = self.workspace_root / agent_name
            
            if agent_path.exists():
                return {
                    "success": False,
                    "error": f"Agent '{agent_name}' already exists"
                }
            
            # Create agent directory
            agent_path.mkdir(parents=True)
            
            # Initialize ADK agent
            env = os.environ.copy()
            env["GRADIENT_MODEL_ACCESS_KEY"] = self.gradient_model_key or ""
            env["DIGITALOCEAN_API_TOKEN"] = self.do_api_token or ""
            
            # Run gradient agent init
            process = await asyncio.create_subprocess_exec(
                "gradient", "agent", "init",
                "--name", agent_name,
                "--deployment", deployment_name,
                cwd=str(agent_path.parent),
                env=env,
                stdout=asyncio.subprocess.PIPE,
                stderr=asyncio.subprocess.PIPE
            )
            
            stdout, stderr = await process.communicate()
            
            if process.returncode != 0:
                return {
                    "success": False,
                    "error": f"Failed to initialize agent: {stderr.decode()}"
                }
            
            # Create custom agent template
            main_py_content = self._generate_agent_template(agent_name, model, description)
            (agent_path / agent_name / "main.py").write_text(main_py_content)
            
            # Create .env file
            env_content = f"""# DigitalOcean ADK Environment Variables
GRADIENT_MODEL_ACCESS_KEY={self.gradient_model_key or ""}
DIGITALOCEAN_API_TOKEN={self.do_api_token or ""}
"""
            (agent_path / agent_name / ".env").write_text(env_content)
            
            # Store agent metadata
            metadata = {
                "agent_name": agent_name,
                "deployment_name": deployment_name,
                "description": description,
                "model": model,
                "created_at": datetime.utcnow().isoformat(),
                "status": "created",
                "path": str(agent_path / agent_name)
            }
            
            (agent_path / agent_name / "agent_metadata.json").write_text(
                json.dumps(metadata, indent=2)
            )
            
            return {
                "success": True,
                "agent": metadata,
                "message": f"Agent '{agent_name}' created successfully"
            }
            
        except Exception as e:
            return {
                "success": False,
                "error": f"Error creating agent: {str(e)}"
            }
    
    def _generate_agent_template(
        self,
        agent_name: str,
        model: str,
        description: str
    ) -> str:
        """Generate agent template code"""
        return f'''"""
{agent_name} - NEXUS AI Agent
{description}

Generated by NEXUS Platform
"""

from langgraph.graph import StateGraph, START, END
from langchain_core.messages import HumanMessage, AIMessage
from typing import TypedDict, List
import os

class AgentState(TypedDict):
    """Agent state definition"""
    messages: List[HumanMessage | AIMessage]
    context: dict

def process_input(state: AgentState) -> AgentState:
    """Process user input"""
    messages = state.get("messages", [])
    context = state.get("context", {{}})
    
    if not messages:
        return state
    
    last_message = messages[-1]
    user_input = last_message.content if hasattr(last_message, 'content') else str(last_message)
    
    # Add your custom agent logic here
    response = f"Agent '{agent_name}' received: {{user_input}}"
    
    messages.append(AIMessage(content=response))
    
    return {{
        "messages": messages,
        "context": context
    }}

def create_agent_graph():
    """Create the agent workflow graph"""
    workflow = StateGraph(AgentState)
    
    # Add nodes
    workflow.add_node("process", process_input)
    
    # Add edges
    workflow.add_edge(START, "process")
    workflow.add_edge("process", END)
    
    return workflow.compile()

# Create agent instance
agent = create_agent_graph()

def run(prompt: str) -> dict:
    """
    Main entrypoint for the agent
    
    Args:
        prompt: User input prompt
        
    Returns:
        Dict with agent response
    """
    try:
        initial_state = {{
            "messages": [HumanMessage(content=prompt)],
            "context": {{}}
        }}
        
        result = agent.invoke(initial_state)
        messages = result.get("messages", [])
        
        if messages:
            last_message = messages[-1]
            response_text = last_message.content if hasattr(last_message, 'content') else str(last_message)
        else:
            response_text = "No response generated"
        
        return {{
            "response": response_text,
            "agent": "{agent_name}",
            "model": "{model}"
        }}
        
    except Exception as e:
        return {{
            "response": f"Error: {{str(e)}}",
            "agent": "{agent_name}",
            "error": True
        }}
'''
    
    async def test_agent_local(
        self,
        agent_name: str,
        prompt: str
    ) -> Dict[str, Any]:
        """
        Test agent locally before deployment
        
        Args:
            agent_name: Name of the agent to test
            prompt: Test prompt
            
        Returns:
            Dict with test results
        """
        try:
            agent_path = self.workspace_root / agent_name / agent_name
            
            if not agent_path.exists():
                return {
                    "success": False,
                    "error": f"Agent '{agent_name}' not found"
                }
            
            # Run agent locally using gradient agent run
            env = os.environ.copy()
            env["GRADIENT_MODEL_ACCESS_KEY"] = self.gradient_model_key or ""
            
            # Start agent server in background
            server_process = await asyncio.create_subprocess_exec(
                "gradient", "agent", "run",
                cwd=str(agent_path),
                env=env,
                stdout=asyncio.subprocess.PIPE,
                stderr=asyncio.subprocess.PIPE
            )
            
            # Wait for server to start
            await asyncio.sleep(3)
            
            # Test the agent
            test_result = await self._call_agent_endpoint(
                "http://localhost:8080/run",
                prompt
            )
            
            # Stop server
            server_process.terminate()
            await server_process.wait()
            
            return {
                "success": True,
                "result": test_result,
                "agent": agent_name
            }
            
        except Exception as e:
            return {
                "success": False,
                "error": f"Error testing agent: {str(e)}"
            }
    
    async def _call_agent_endpoint(
        self,
        endpoint: str,
        prompt: str
    ) -> Dict[str, Any]:
        """Call agent endpoint"""
        import aiohttp
        
        async with aiohttp.ClientSession() as session:
            async with session.post(
                endpoint,
                json={"prompt": prompt},
                headers={"Content-Type": "application/json"}
            ) as response:
                return await response.json()
    
    async def deploy_agent(
        self,
        agent_name: str,
        deployment_name: str = "development"
    ) -> Dict[str, Any]:
        """
        Deploy agent to DigitalOcean
        
        Args:
            agent_name: Name of the agent to deploy
            deployment_name: Deployment environment name
            
        Returns:
            Dict with deployment status and URL
        """
        try:
            agent_path = self.workspace_root / agent_name / agent_name
            
            if not agent_path.exists():
                return {
                    "success": False,
                    "error": f"Agent '{agent_name}' not found"
                }
            
            if not self.do_api_token:
                return {
                    "success": False,
                    "error": "DIGITALOCEAN_API_TOKEN not configured"
                }
            
            # Deploy using gradient agent deploy
            env = os.environ.copy()
            env["GRADIENT_MODEL_ACCESS_KEY"] = self.gradient_model_key or ""
            env["DIGITALOCEAN_API_TOKEN"] = self.do_api_token
            
            process = await asyncio.create_subprocess_exec(
                "gradient", "agent", "deploy",
                "--deployment", deployment_name,
                cwd=str(agent_path),
                env=env,
                stdout=asyncio.subprocess.PIPE,
                stderr=asyncio.subprocess.PIPE
            )
            
            stdout, stderr = await process.communicate()
            
            if process.returncode != 0:
                return {
                    "success": False,
                    "error": f"Deployment failed: {stderr.decode()}"
                }
            
            # Parse deployment URL from output
            output = stdout.decode()
            deployment_url = self._extract_deployment_url(output)
            
            # Update agent metadata
            metadata_file = agent_path.parent / "agent_metadata.json"
            if metadata_file.exists():
                metadata = json.loads(metadata_file.read_text())
                metadata["status"] = "deployed"
                metadata["deployment_url"] = deployment_url
                metadata["deployed_at"] = datetime.utcnow().isoformat()
                metadata_file.write_text(json.dumps(metadata, indent=2))
            
            return {
                "success": True,
                "deployment_url": deployment_url,
                "agent": agent_name,
                "deployment": deployment_name,
                "message": "Agent deployed successfully"
            }
            
        except Exception as e:
            return {
                "success": False,
                "error": f"Error deploying agent: {str(e)}"
            }
    
    def _extract_deployment_url(self, output: str) -> str:
        """Extract deployment URL from gradient CLI output"""
        for line in output.split('\n'):
            if 'https://agents.do-ai.run' in line:
                # Extract URL
                parts = line.split()
                for part in parts:
                    if part.startswith('https://agents.do-ai.run'):
                        return part
        return ""
    
    async def call_deployed_agent(
        self,
        deployment_url: str,
        prompt: str
    ) -> Dict[str, Any]:
        """
        Call a deployed agent
        
        Args:
            deployment_url: URL of the deployed agent
            prompt: User prompt
            
        Returns:
            Dict with agent response
        """
        try:
            import aiohttp
            
            headers = {
                "Authorization": f"Bearer {self.do_api_token}",
                "Content-Type": "application/json"
            }
            
            async with aiohttp.ClientSession() as session:
                async with session.post(
                    deployment_url,
                    json={"prompt": prompt},
                    headers=headers
                ) as response:
                    result = await response.json()
                    return {
                        "success": True,
                        "result": result
                    }
                    
        except Exception as e:
            return {
                "success": False,
                "error": f"Error calling agent: {str(e)}"
            }
    
    def list_agents(self) -> List[Dict[str, Any]]:
        """List all created agents"""
        agents = []
        
        try:
            for agent_dir in self.workspace_root.iterdir():
                if agent_dir.is_dir():
                    metadata_file = agent_dir / agent_dir.name / "agent_metadata.json"
                    if metadata_file.exists():
                        metadata = json.loads(metadata_file.read_text())
                        agents.append(metadata)
            
            return agents
            
        except Exception as e:
            print(f"Error listing agents: {e}")
            return []
    
    def get_agent(self, agent_name: str) -> Optional[Dict[str, Any]]:
        """Get agent details"""
        try:
            metadata_file = self.workspace_root / agent_name / agent_name / "agent_metadata.json"
            if metadata_file.exists():
                return json.loads(metadata_file.read_text())
            return None
        except Exception:
            return None
    
    async def delete_agent(self, agent_name: str) -> Dict[str, Any]:
        """Delete an agent"""
        try:
            agent_path = self.workspace_root / agent_name
            
            if not agent_path.exists():
                return {
                    "success": False,
                    "error": f"Agent '{agent_name}' not found"
                }
            
            # Remove agent directory
            shutil.rmtree(agent_path)
            
            return {
                "success": True,
                "message": f"Agent '{agent_name}' deleted successfully"
            }
            
        except Exception as e:
            return {
                "success": False,
                "error": f"Error deleting agent: {str(e)}"
            }
    
    def get_agent_logs(self, agent_name: str) -> Dict[str, Any]:
        """Get agent logs"""
        try:
            agent_path = self.workspace_root / agent_name / agent_name
            log_file = agent_path / "agent.log"
            
            if log_file.exists():
                logs = log_file.read_text()
                return {
                    "success": True,
                    "logs": logs
                }
            
            return {
                "success": True,
                "logs": "No logs available"
            }
            
        except Exception as e:
            return {
                "success": False,
                "error": f"Error reading logs: {str(e)}"
            }

# Create global instance
adk_service = DigitalOceanADKService()
