"""
GitHub Integration Service
Auto-creates PRs for autonomous development tasks
"""
import logging
import os
import subprocess
from typing import Dict, Any, Optional
from datetime import datetime, timezone
import httpx

logger = logging.getLogger(__name__)

class GitHubIntegrationService:
    """
    Integrates with GitHub to:
    - Create branches for autonomous tasks
    - Commit generated code
    - Create pull requests
    - Auto-merge when tests pass
    """
    
    def __init__(self):
        self.github_token = os.getenv('GITHUB_TOKEN', '')
        self.repo_owner = os.getenv('GITHUB_REPO_OWNER', '')
        self.repo_name = os.getenv('GITHUB_REPO_NAME', '')
        self.enabled = bool(self.github_token and self.repo_owner and self.repo_name)
        
        if self.enabled:
            logger.info(f"✓ GitHub integration enabled: {self.repo_owner}/{self.repo_name}")
        else:
            logger.info("GitHub integration disabled (set GITHUB_TOKEN, GITHUB_REPO_OWNER, GITHUB_REPO_NAME)")
    
    async def create_pull_request(
        self,
        task_description: str,
        branch_name: str,
        file_changes: Dict[str, str],
        auto_merge: bool = False
    ) -> Dict[str, Any]:
        """
        Create a pull request for autonomous task.
        
        Args:
            task_description: Description of the task
            branch_name: Name for the new branch
            file_changes: Dict of {file_path: content}
            auto_merge: Whether to auto-merge if tests pass
        """
        if not self.enabled:
            return {"success": False, "error": "GitHub integration not configured"}
        
        try:
            # 1. Create branch
            await self._create_branch(branch_name)
            
            # 2. Commit changes
            for file_path, content in file_changes.items():
                await self._commit_file(branch_name, file_path, content, f"Auto: Update {file_path}")
            
            # 3. Create PR
            pr_url = await self._create_pr(
                branch_name,
                f"🤖 Auto: {task_description}",
                f"This PR was automatically generated by NEXUS Autonomous Development System.\n\n**Task**: {task_description}\n\n**Changes**:\n" + "\n".join(f"- {path}" for path in file_changes.keys())
            )
            
            return {
                "success": True,
                "pr_url": pr_url,
                "branch": branch_name,
                "auto_merge": auto_merge
            }
        except Exception as e:
            logger.error(f"Failed to create PR: {e}")
            return {"success": False, "error": str(e)}
    
    async def _create_branch(self, branch_name: str):
        """Create a new branch"""
        # Get default branch SHA
        async with httpx.AsyncClient() as client:
            response = await client.get(
                f"https://api.github.com/repos/{self.repo_owner}/{self.repo_name}/git/refs/heads/main",
                headers={"Authorization": f"token {self.github_token}"}
            )
            main_sha = response.json()["object"]["sha"]
            
            # Create new branch
            await client.post(
                f"https://api.github.com/repos/{self.repo_owner}/{self.repo_name}/git/refs",
                headers={"Authorization": f"token {self.github_token}"},
                json={
                    "ref": f"refs/heads/{branch_name}",
                    "sha": main_sha
                }
            )
    
    async def _commit_file(self, branch_name: str, file_path: str, content: str, message: str):
        """Commit a file to branch"""
        import base64
        
        async with httpx.AsyncClient() as client:
            # Get file SHA if exists
            try:
                response = await client.get(
                    f"https://api.github.com/repos/{self.repo_owner}/{self.repo_name}/contents/{file_path}?ref={branch_name}",
                    headers={"Authorization": f"token {self.github_token}"}
                )
                sha = response.json().get("sha")
            except:
                sha = None
            
            # Update/create file
            data = {
                "message": message,
                "content": base64.b64encode(content.encode()).decode(),
                "branch": branch_name
            }
            if sha:
                data["sha"] = sha
            
            await client.put(
                f"https://api.github.com/repos/{self.repo_owner}/{self.repo_name}/contents/{file_path}",
                headers={"Authorization": f"token {self.github_token}"},
                json=data
            )
    
    async def _create_pr(self, branch_name: str, title: str, body: str) -> str:
        """Create pull request"""
        async with httpx.AsyncClient() as client:
            response = await client.post(
                f"https://api.github.com/repos/{self.repo_owner}/{self.repo_name}/pulls",
                headers={"Authorization": f"token {self.github_token}"},
                json={
                    "title": title,
                    "body": body,
                    "head": branch_name,
                    "base": "main"
                }
            )
            return response.json()["html_url"]
    
    async def merge_pr(self, pr_number: int) -> bool:
        """Auto-merge PR"""
        try:
            async with httpx.AsyncClient() as client:
                response = await client.put(
                    f"https://api.github.com/repos/{self.repo_owner}/{self.repo_name}/pulls/{pr_number}/merge",
                    headers={"Authorization": f"token {self.github_token}"},
                    json={
                        "commit_title": "Auto-merge: Autonomous development task",
                        "merge_method": "squash"
                    }
                )
                return response.status_code == 200
        except Exception as e:
            logger.error(f"Failed to merge PR: {e}")
            return False

# Singleton
github_integration = GitHubIntegrationService()
