#!/bin/bash
# Complete Cloudflare Setup - All Steps
# Token: cfat_A3gq1xqMrVXBtWQN7cqOaNuFSiFS4RBGRsqezGXEd3e6d497
# Account: 9ea3a006589428efed0480da5c037163

TOKEN="cfat_A3gq1xqMrVXBtWQN7cqOaNuFSiFS4RBGRsqezGXEd3e6d497"
ACCOUNT_ID="9ea3a006589428efed0480da5c037163"
DOMAIN="nexussocialmarket.com"
EMERGENT_URL="model-exchange-2.preview.emergentagent.com"

echo "🚀 Complete Cloudflare Setup for NEXUS"
echo "========================================="
echo ""

echo "Step 1: Add Domain to Cloudflare"
echo "---------------------------------"
echo "⚠️  This requires manual action in Cloudflare Dashboard:"
echo ""
echo "1. Go to: https://dash.cloudflare.com/9ea3a006589428efed0480da5c037163"
echo "2. Click: 'Add a site'"
echo "3. Enter: nexussocialmarket.com"
echo "4. Choose: Free plan"
echo "5. Click: 'Add site'"
echo ""
echo "Cloudflare will provide nameservers. Copy them."
echo ""
echo "6. Go to your domain registrar (where you bought the domain)"
echo "7. Update nameservers to Cloudflare's"
echo "8. Wait 5-15 minutes for Cloudflare to verify"
echo ""
echo "After domain is active, run this command:"
echo ""
echo "  ZONE_ID=\$(curl -s 'https://api.cloudflare.com/client/v4/zones?name=nexussocialmarket.com' \\"
echo "    -H 'Authorization: Bearer $TOKEN' | \\"
echo "    python3 -c 'import sys,json; z=json.load(sys.stdin).get(\"result\",[]); print(z[0][\"id\"] if z else \"\")')"
echo ""
echo "  echo \"Zone ID: \$ZONE_ID\""
echo ""
echo "Once you have the ZONE_ID, I'll configure everything automatically!"
echo ""
echo "========================================="
echo ""
echo "💡 Alternative: Use Emergent Native"
echo "========================================="
echo ""
echo "For immediate deployment (no Cloudflare account setup):"
echo ""
echo "1. Open Emergent Dashboard"
echo "2. Click 'Link domain'"
echo "3. Enter: www.nexussocialmarket.com"
echo "4. Click 'Use Entri'"
echo "5. Wait 5-15 minutes"
echo "6. ✅ Live at www.nexussocialmarket.com!"
echo ""
echo "This is MUCH faster (15 mins vs 1-2 days) and requires zero manual setup!"
echo ""
